@mainUrl = http://localhost:3000

###
#
POST  {{mainUrl}}/status2/add-new-list
Content-Type: application/json

{
    "name": "test"
}

###
#
DELETE   {{mainUrl}}/status2/delete-list
Content-Type: application/json

{
    "id": "1"
}

###
#
GET {{mainUrl}}/status2

###
#
POST {{mainUrl}}/status2/add-new-task
Content-Type: application/json

{
    "listId": "2",
    "name": "taskName"
}